### ISSUE TITLE
Failed to restore cache

### ISSUE THREAD

**Issue by jonsterling** [teatimeguest/setup-texlive-action#255]
I have suddenly been having a problem with the cache that this action is creating; my build reports the following error when restoring the cache:

```
Warning: Failed to restore: Expected signal to be an instanceof AbortSignal
```

See https://github.com/jonsterling/forest/actions/runs/5625610458/job/15244745000 for an example build. I wonder what's going on?

**Comment by muzimuzhi** [comment]
Maybe related: https://github.com/actions/toolkit/issues/687

**Comment by teatimeguest** [comment]
Thank you for reporting!

I have now released a patched version that should fix this problem. Please try re-running your workflow.

**Comment by jonsterling** [comment]
@teatimeguest Thanks so much for moving so quickly! My workflow now runs correctly.
