### ISSUE TITLE
Frequent failure to check latest TeXlive version

### ISSUE THREAD

**Issue by jonsterling** [teatimeguest/setup-texlive-action#310]
I'm getting this error about one third to half the time I run this action:

    Failed to check for latest version: Error: Request timeout: /json/2.0/pkg/texlive
    Use `2023` as latest version

This started happening a few weeks ago. Because it chooses 2023 by default, I then get a further error:
```
UnexpectedVersion: Unexpected install-tl version: 2024
    at UnexpectedVersion.check (file:///home/runner/work/_actions/teatimeguest/setup-texlive-action/v2/dist/index.mjs:62275:11)
    at async download (file:///home/runner/work/_actions/teatimeguest/setup-texlive-action/v2/dist/index.mjs:62693:7)
    at async acquire (file:///home/runner/work/_actions/teatimeguest/setup-texlive-action/v2/dist/index.mjs:62660:36)
    at async installTL (file:///home/runner/work/_actions/teatimeguest/setup-texlive-action/v2/dist/index.mjs:62632:25)
    at async file:///home/runner/work/_actions/teatimeguest/setup-texlive-action/v2/dist/index.mjs:63316:9 {
  version: '2023',
  repository: 'https://us.mirrors.cicku.me/ctan/systems/texlive/tlnet/',
  remoteVersion: '2024'
}
```

**Comment by teatimeguest** [comment]
@jonsterling Since [`v3.2.0`](https://github.com/teatimeguest/setup-texlive-action/releases/tag/v3.2.0), TeX Live 2024 is the default. Perhaps you are using an older version?

**Comment by teatimeguest** [comment]
@jonsterling The log shows that you are still using v2:
> ```console
> at UnexpectedVersion.check (file:///home/runner/work/_actions/teatimeguest/setup-texlive-action/v2/dist/index.mjs:62275:11)
> ```
Please consider upgrading to v3. Breaking changes are listed [here](https://github.com/teatimeguest/setup-texlive-action#breaking-changes-in-v3), but in most cases no changes to your workflow are required.

**Comment by teatimeguest** [comment]
> This started happening a few weeks ago.

This may indicate that [CTAN](https://ctan.org) has recently become unstable (CTAN had previously announced that it was being targeted by spammers). If this is the case, a similar error may occur even with v3, as this action uses the CTAN API not only to check latest version but also to resolve package names. I will consider some workaround.

**Comment by jonsterling** [comment]
@teatimeguest Oh, thanks very much! I'll try upgrading to v3.

**Comment by jonsterling** [comment]
I'm going to close this ticket — the new version seems to work well. Thanks again for your help!
