### ISSUE TITLE
Default branch cache is not available to other branches

### ISSUE THREAD

**Issue by muzimuzhi** [teatimeguest/setup-texlive-action#320]
It seems a job ran on a new feature branch always created its own cache, even when a cache saved for the default branch existed. See for example [this run](https://github.com/muzimuzhi/tabularray/actions/runs/11242555886/job/31256493149#step:3:12).

This behavior is different from that of the `actions/cache` action, in which "The default branch cache is available to other branches" (see [its doc on cache scopes](https://github.com/actions/cache?tab=readme-ov-file#cache-scopes)).

**Comment by teatimeguest** [comment]
Thank you for your report.

I would like to keep the behavior as close as possible to those of official actions, but there appears to be no API in the [`@actions/cache`](https://github.com/actions/toolkit/tree/main/packages/cache) package to change this behavior. I have also checked the [source code](https://github.com/actions/cache/blob/main/src/restoreImpl.ts) of actions/cache, but could not find anything special about it. So, I do not know why this difference occurs and cannot address it at this time.

Could there be some other condition involved? (e.g., cache and branch creation time, workflow permissions, etc)

**Comment by teatimeguest** [comment]
@muzimuzhi The default branch of your repository is `develop`, and the [cache list](https://github.com/muzimuzhi/tabularray/actions/caches) shows that no cache is stored for this branch; the `main` branch certainly has a cache entry, but not the default.

Maybe this is the cause? (unless you have changed the default branch or deleted caches on `develop`)

**Comment by muzimuzhi** [comment]
> @muzimuzhi The default branch of your repository is `develop`, and the [cache list](https://github.com/muzimuzhi/tabularray/actions/caches) shows that no cache is stored for this branch; the `main` branch certainly has a cache entry, but is not the default.

Oh my. Thank you very much for pointing out this subtle difference as I seldom change default branch in forks. Thanks again and sorry for the noise.
